config/routes.rb
Rails.application.routes.draw do
  root to: 'tasklists#index'
  resources :tasklists
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  def index
     @tasklists = Tasklist.all
  end

  def show
     @tasklist = Tasklist.find(params[:id])
  end

  def new
      @tasklist = Tasklist.new
    
  end

  def create
    @tasklist = Tasklist.new(tasklist_params)

    if @tasklist.save
      flash[:success] = 'Tasklist が正常に投稿されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'Tasklist が投稿されませんでした'
      render :new
    end
  end
  
  def edit
    @tasklist = Tasklist.find(params[:id])
  end
  
  def update
     @tasklist = Tasklist.find(params[:id])

    if @tasklist.update(tasklist_params)
      flash[:success] = 'Tasklist は正常に更新されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'Tasklist は更新されませんでした'
      render :edit
    end
  end
   
  def destroy
    set_tasklist
    @tasklist.destroy

    flash[:success] = 'Tasklist は正常に削除されました'
    redirect_to tasklists_url
  end
private
    def set_tasklist
    @tasklist = Tasklist.find(params[:id])
    end
  # Strong Parameter
  def tasklist_params
    params.require(:tasklist).permit(:content, :statuss)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/views/layouts/_flash_tasklists.html.erb
<% flash.each do |tasklist_type, tasklist| %>

  <div>
<%= tasklist %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasklists/_form.html.erb
<%= form_for(tasklist) do |f| %>

  
<% if tasklist.errors.any? %>

    <div id="error_explanation">
     
     
      <ul>
        <% tasklist.errors.full_messages.each do |tasklist| %>
          <li><%= tasklist %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<%= f.label :status, 'ステータス' %>

  
<%= f.text_field :status %>

  
  
<%= f.label :content, 'タスクリスト' %>

  
<%= f.text_field :content %>

<%= f.submit '投稿' %>

<% end %>

app/views/tasklists/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    
    
<%= csrf_meta_tags %>


    
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      
<%= render 'layouts/flash_tasklist' %>


      
<%= yield %>

    </div>
  </body>
</html>

app/views/tasklists/edit.html.erb
<h1>id: 
<%= @tasklist.id %>
 のタスクリスト編集ページ</h1>



<%= render 'form', tasklist: @tasklist %>


<%= link_to '一覧に戻る', tasklists_path %>

app/views/tasklists/index.html.erb
<h1>タスクリスト一覧</h1>

<ul>
  
<% @tasklists.each do |tasklist| %>

    <li>
<%= link_to tasklist.id, tasklist %>
 : 
 > 
<%= tasklist.content %>
 >
<%= tasklist.status %>
</li>
  
<% end %>

</ul>

<%= link_to '新規メッセージの投稿', new_tasklist_path %>

app/views/tasklists/new.html.erb
<h1>タスクリスト新規作成ページ</h1>


<%= render 'form', tasklist: @tasklist %>


<%= link_to '一覧に戻る', tasklists_path %>

app/views/tasklists/show.html.erb
<h1>id = 
<%= @tasklist.id %>
 のタスクリスト詳細ページ</h1>
 
<p>タスクリスト: <%= @tasklist.content %></p>
<p>ステータス: <%= @tasklist.status%></p>



<%= link_to '一覧に戻る', tasklists_path %>

<%= link_to 'このタスクリストを編集する', edit_tasklist_path(@tasklist) %>

<%= link_to 'このタスクリストを削除する', @tasklist, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>